services:
  backend:
    build:
      context: ./backend
    container_name: compose-backend
    networks:
      testnet:
        ipv4_address: 192.168.200.10
    ports:
      - "8081:8080"
    depends_on:
      - compose-device1
      - compose-device2

  compose-device1:
    image: alpine
    container_name: compose-device1
    hostname: device1
    command: ["sleep", "infinity"]
    networks:
      testnet:
        ipv4_address: 192.168.200.11

  compose-device2:
    image: alpine
    container_name: compose-device2
    hostname: device2
    command: ["sleep", "infinity"]
    networks:
      testnet:
        ipv4_address: 192.168.200.12

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
